# Generated by Django 5.1.6 on 2025-03-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('photo_device', models.ImageField(blank=True, help_text='يجب ان تكون بصيغة jpg or png or webp', null=True, upload_to='photos')),
                ('photo_company', models.ImageField(blank=True, help_text='يجب ان تكون بصيغة jpg or png or webp', null=True, upload_to='photos')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rental_money', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('type_device', models.CharField(blank=True, choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], max_length=50, null=True)),
                ('rental_price_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rental_period', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_rental', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'available'), ('rental', 'rental'), ('sold', 'sold')], max_length=50, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.category')),
            ],
        ),
    ]
